---@module CustomAssets

local class = require 'r35_tts.middleclass'
local CustomAssets = class('CustsomAssets')

local _data = {
  ["Add Character"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/AddCharacter.png",
  ["+ Sign"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/PlusSign.png",
  ["BI Drawer"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/BIDrawer.png",
  Checkmark = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Checkmark.png",
  ["Draw Modifier"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/DrawModifier.png",
  ["End Round"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/EndRound.png",
  ["Initiative Drawer"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/InitiativeDrawer.png",
  ["Long Rest"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/LongRest.png",
  P1 = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/P1.png",
  P2 = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/P2.png",
  P3 = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/P3.png",
  P4 = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/P4.png",
  ["Solo Mode"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/SoloMode.png",
  ["Sort Hand"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/SortHand.png",
  ["Start Round"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/StartRound.png",
  ["BI Text"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/BIText.png",
  Percentage = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Percentage.png",
  ["X Sign"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/XSign.png",
  ArrowRight = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ArrowRight.png",
  ArrowLeft = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ArrowLeft.png",
  ["Rule Book"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/RuleBook.png",
  ["Scenario Book"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ScenarioBook.png",
  ["3D Overlay"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/3DOverlay.png",
  ["Create Map"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/CreateMap.png",
  ["Delete Map"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/DeleteMap.png",
  ["Delete Monsters"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/DeleteMonsters.png",
  Elite = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Elite.png",
  ["Game Setup"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/GameSetup.png",
  ["Hidden Rooms"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/HiddenRooms.png",
  ["Monster Setup"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/MonsterSetup.png",
  ["Monster Setup Selected"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/MonsterSetupSelected.png",
  ["Radio Button"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/RadioButton.png",
  ["Radio Button Selected"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/RadioButtonSelected.png",
  ["Revealed Rooms"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/RevealedRooms.png",
  ["Scenario Level"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ScenarioLevel.png",
  ["Scenario Number"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ScenarioNumber.png",
  ["Scenario Setup"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ScenarioSetup.png",
  ["Scenario Setup Selected"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/ScenarioSetupSelected.png",
  ["Spawn Monster"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/SpawnMonster.png",
  ["Want Delete"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/WantDelete.png",
  Yes = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Yes.png",
  No = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/No.png",
  Index = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Index.png",
  Tracker = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Tracker.png",
  Regenerate = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Regenerate.png",
  ["S"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/S.png",
  ["Add Target"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/AddTarget.png",
  ["Attack-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Attack-W.png",
  ["Shield-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Shield-W.png",
  ["Retaliate-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Retaliate-W.png",
  ["Range-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Range-W.png",
  ["Move-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Move-W.png",
  ["Loot-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Loot-W.png",
  ["Health-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Health-W.png",
  ["Flight-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Flight-W.png",
  Curse = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Curse.png",
  Pierce = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Pierce.png",
  Push = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Push.png",
  Bless = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Bless.png",
  Pull = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Pull.png",
  ["Targets-W"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Targets-W.png",
  Win = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Win.png",
  Lost = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Lost.png",
  ["Camera Controls"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/CameraControls.png",
  ["Play Area"] = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/PlayArea.png",
  Scenario = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Scenario.png",
  One = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/One.png",
  Two = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Two.png",
  Three = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Three.png",
  Four = "https://cdn.r35.net/tts/gloomhaven/custom_ui_assets/Four.png"
}

function CustomAssets:has()
end

return CustomAssets
