describe("Tests HexColor", function()
  describe("can be initialized", function()
    local HexColor = require("hexcolor")

    it("accepts a 6-character representation without the leading pound sign", function()
      local tmp = HexColor:new("FF0000")
      local output = tmp:rgb()
      assert.are.equal(output.r, 1)
      assert.are.equal(output.g, 0)
      assert.are.equal(output.b, 0)
      assert.is_nil(output.a)
    end)
  end)
end)
